import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>松井梨沙のポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/my_picture.jpg" />
      </Head>

      <header className={styles.header}>

        <h1 className={styles.title}>
          <Link href="#welcome">
            <a>ホーム</a>
          </Link>
        </h1>

        <div className={styles.spacer}/>

        <nav className="nav">
          <ul className={styles.menu_group}>

            <li className="menu-item">
              <Link href="#introduce">
                <a>自己紹介</a>
              </Link>
            </li>

            <li className="menu-item">
              <Link href="#sports">
                <a>スポーツ</a>
              </Link>
            </li>

            <li className="menu-item">
              <Link href="#like">
                <a>好きな○○</a>
              </Link>
            </li>

          </ul>
        </nav>

      </header>

      <main className={styles.main}>
        
        <div className={styles.welcome} id="welcome">
          <div className={styles.myPicture}>
          <Image src="/image/my_picture.jpg" alt="myPicture" width={350} height={500}/>
          </div>
        
          <div className={styles.welcomeSentence}>
            <h1 className={styles.mainTitle}>
              Welcome to <br />my-portfolio!!
            </h1>

            <p className={styles.hello}>
            松井梨沙です！よろしくお願いします！
            </p>

            <div className={styles.mainButton}>
              <button className={styles.introduceButton} onClick="#">自己紹介</button>
              <button className={styles.sportsButton} onClick="#">スポーツ</button>
              <button className={styles.likeButton} onClick="#">好きな○○</button>
            </div>
          </div>
        </div>


        {/*自己紹介のページ-------------------------------------------*/}

        <div className={styles.introduce} id="introduce">

        <h2 className={styles.introduceTitle}>
          自己紹介
        </h2>

          <div className={styles.nameGroup}>
            <div className={styles.name}><strong>名前</strong></div>
            <p className={styles.nameSentence}>松井梨沙 （マツイ　リサ）</p>
          </div>

          <div className={styles.majorGroup}>
            <p className={styles.major}><strong>所属</strong></p>
            <p className={styles.majorSentence}>静岡大学/情報学部/情報社会学科/2年</p>
          </div>

          <div className={styles.futureGroup}>
            <p className={styles.future}><strong>将来</strong></p>
            <p className={styles.futureSentence}>情報関連の仕事をしたい</p>
          </div>

          <div className={styles.hobbyGroup}>
            <p className={styles.hobby}><strong>趣味</strong></p>
              <ul className={styles.hobbySentence}>
                <li>韓国ドラマを見ること</li>
                <li>K-POPを聴くこと</li>
                <li>東海オンエアというYouTuberの動画を見ること</li>
                  {/*<p><a href="#" >（私の趣味ついて:URL）</a></p>*/}
              </ul>
          </div>

          <div className={styles.personalityGroup}>
            <p className={styles.personality}><strong>自分の性格</strong></p>
              <ul className={styles.personalitySentence}>
                <li>地道な作業を黙々とこなす</li>
                <li>人見知り</li>
                <li>真面目,責任感が強い</li>
                <li>マイペース</li>
              </ul>
          </div>
        </div>

        {/*自己紹介のページ終わり-------------------------------------------*/}


        {/*スポーツのページ-------------------------------------------*/}
          <div className={styles.sports} id="sports">

            <h2 className={styles.sportsTitle}>
              スポーツ
            </h2>
            <p className={styles.sportscomment}>
              私が今まで練習してきたスポーツを紹介します
            </p>

            <div className={styles.basketball}>
              <p className={styles.basketballWord}>
                バスケットボール
              </p>
              <div className={styles.sports1}> 
                <button className={styles.elementarySchool} onClick="#"><strong>小学校</strong></button>
                <div className={styles.basketballPicture}/>
              </div>
            </div>
      
            <div className={styles.softball}> 
              <div className={styles.sports2}> 
                <button className={styles.jHighSchool} onClick="#"><strong>中学校</strong></button>
                <div className={styles.softballPicture}/>
              </div>
              <p className={styles.softballWord}>
                ソフトボール
              </p>
            </div>

            <div className={styles.tennis}>
              <p className={styles.tennisWord}>
                硬式テニス
              </p>
              <div className={styles.sports3}> 
                <button className={styles.highSchool} onClick="#"><strong>高校</strong></button>
                <div className={styles.tennisPicture}/>
              </div>
            </div>

            <div className={styles.volleyball}> 
              <div className={styles.sports4}> 
                <button className={styles.university} onClick="#"><strong>大学</strong></button>
                <div className={styles.volleyballPicture}/>
              </div>
              <p className={styles.volleyballWord}> 
                バレーボール
              </p>
            </div>

          </div> 
          

        {/*スポーツのページ終わり-------------------------------------------*/}







        {/*好きな○○のページ-------------------------------------------*/}

        <div className={styles.like} id="like">

          <h2 className={styles.likeTitle}>
            好きな○○
          </h2>
          <p className={styles.likecomment}>
            私が好きなものを様々なジャンルから紹介します
          </p>

          <div className={styles.sushi}>
            <p className={styles.sushiExplain}>
              <strong>寿司</strong><br/>
              月２回くらいは回転寿司に行きます<br/>
              好きなネタはマグロ、サーモン、ホタテです
            </p>
            <div className={styles.like1}> 
              <button className={styles.likeFood} onClick="#"><strong>好きな食べ物</strong></button>
              <div className={styles.sushiPicture}/>
            </div>
          </div>

          <div className={styles.okinawa}> 
            <div className={styles.like2}> 
              <button className={styles.likePlace} onClick="#"><strong>好きな場所</strong></button>
              <div className={styles.okinawaPicture}/>
            </div>
            <p className={styles.okinawaExplain}>
              <strong>沖縄</strong><br/>
              沖縄には5、6回行ったことがあります<br/>
              オススメスポットは座間味島です
            </p>
          </div>

          <div className={styles.kamaitati}>
            <p className={styles.kamaitatiExplain}>
              <strong>かまいたち</strong><br/>
                山内のサイコパスなお笑い、最高！
            </p>
            <div className={styles.like3}> 
              <button className={styles.likePeople} onClick="#"><strong>好きな芸人</strong></button>
              <div className={styles.kamaitatiPicture}/>
            </div>
          </div>

          <div className={styles.manga}> 
            <div className={styles.like4}> 
              <button className={styles.likeManga} onClick="#"><strong>好きな漫画</strong></button>
              <div className={styles.mangaPicture}/>
            </div>
            <p className={styles.mangaExplain}> 
              <strong>宇宙兄弟</strong><br/>
                面白いのに、時々はっとさせられる<br/>
                ようなセリフがあるところが好きです
            </p>
          </div>

        </div> 

      {/*好きな○○のページ終わり-------------------------------------------*/}

      </main>

    </div>
  )
}
